# Generated by Django 2.2.1 on 2019-05-25 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Должность',
            },
        ),
        migrations.CreateModel(
            name='InformationEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('employment_day', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Position')),
            ],
            options={
                'verbose_name_plural': 'Информация о  сотрудниках',
                'verbose_name': 'Информация о каждом сотруднике',
            },
        ),
    ]
