# Generated by Django 2.2.1 on 2019-05-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_informationemployee_chief'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationemployee',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
